### ISSUE TITLE
Need -fPIC build flag in linux platform

### ISSUE THREAD

**Issue by DaviesX** [cierelabs/json_spirit#26]
The static library is not relocatable if not compiled with -fPIC.

**Comment by DaviesX** [comment]
```
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -fPIC")
```

**Comment by jefftrull** [comment]
Thanks for your question.  Normally static libraries don't require relocation, and -fPIC produces larger and less efficient code.

Are you trying to create a shared library that includes json_spirit?  If so you can do this:

`set_target_properties( json PROPERTIES POSITION_INDEPENDENT_CODE TRUE )`
